[package]
name = "tattoo"
version = "0.3.1"
edition = "2021"

[lib]
name = "tattoo_lib"
path = "src/lib.rs"

[dependencies]
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
winreg = "0.50.0"
