[package]
name = "tattoo"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
winreg = "0.50.0"
