[package]
name = "tattoo"
version = "0.2.3"
edition = "2021"

[lib]
name = "tattoo"
path = "src/lib.rs"

[[bin]]
name = "tatto_bin"
path = "src/main.rs"

[dependencies]
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
winreg = "0.50.0"
