[package]
name = "tattoo"
version = "0.4.1"
edition = "2021"
authors = [ "Joshua Winters-Brown" ]
readme = "README.md"
repository = "https://github.com/ofgrenudo/tattoo"
license-file = "LICENSE.md"

[lib]
name = "tattoo_lib"
path = "src/lib.rs"

[dependencies]
native-windows-derive = "1.0.5"
native-windows-gui = "1.0.13"
winreg = "0.50.0"
