import { HorizontalBox, VerticalBox, Button, LineEdit, TextEdit} from "std-widgets.slint";
export global SystemInformation {
    in-out property <string> manufacturer: "Null";
    in-out property <string> model: "Null";
    in-out property <string> serial_number: "Null";
    in-out property <string> status: "Null";
    in-out property <string> asset_tag: "Null";
    in-out property <string> button_response: "Submitted";
    in-out property <bool> button_enabled: false;
    callback information-submitted(string, string);
    callback asset_tag_edited(string);
    callback status_edited(string);
}
export component AppWindow inherits Window {
    min-height: 380px;
    max-height: 380px;
    min-width: 500px;
    max-width: 500px;
    always-on-top: true;
    // default-font-size: 14px;
    title: "Tattoo";

    VerticalBox {
        
        HorizontalBox {
            spacing: 50px;
            Text { text: "Manufacturer"; vertical-alignment: center; font-size: 14px;}
            LineEdit { text: SystemInformation.manufacturer; height: 40px; read-only: true; }
        }
        
        HorizontalBox {
            spacing: 93px;
            Text { text: "Model"; vertical-alignment: center; font-size: 14px;}
            LineEdit { text: SystemInformation.model; height: 40px; read-only: true; }
        }
        
        HorizontalBox {
            spacing: 42px;
            Text { text: "Serial Number"; vertical-alignment: center; font-size: 14px;}
            LineEdit { text: SystemInformation.serial-number; height: 40px; read-only: true; }
        }
        
        HorizontalBox {
            spacing: 92px;
            Text { text: "Status"; vertical-alignment: center; font-size: 14px;}
            LineEdit { text: SystemInformation.status; height: 40px; read-only: false; edited => {
              SystemInformation.status_edited(self.text);
            }}
        }

        HorizontalBox {
            spacing: 69px;
            Text { text: "Asset Tag"; vertical-alignment: center; font-size: 14px;}
            LineEdit { text: SystemInformation.asset-tag; height: 40px; read-only: false; edited => {
              SystemInformation.asset_tag_edited(self.text);
            }}
        }

        HorizontalBox {
            Button { 
              text: SystemInformation.button_response;
              enabled: SystemInformation.button_enabled;
              clicked => {
                SystemInformation.information-submitted(SystemInformation.asset-tag, SystemInformation.status);
              }
            }
        }
    }
}
